### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#138]
# What to look for in review
- Style / grammar
   - grammarly
   - hemmingwayapp
   - typely
   - espresso-app
- What's missing from the sections and paper overall.
- Consistency within examples (do the same example problems get used throughout the paper?)
- Consistency of causal graphs between sections
   - What graphs are used?
   - Do we use conventions for observed / unobserved variables as squares and circle node shapes?
- Any unfulfilled promises from beginning of sections to the end of the sections and across sections?
- (At end) reference or discuss other going-ons in causal inference and in transportation.

**Comment by bouzaghrane** [comment]
Set of questions during review:

# Before Reading:
- Hassan:
   - Do headers for subsections cover the overall message of the latent confounding section
- Amine:
   - What is the purpose of the simulation of selection on observables?
- Tim:
   - Does the structure of the sections convey the general point of the section?
   - Are the sections' contributions clear? If someone wants to skim.
- All:
   - Are any images small or large, are all graphs consistent (the way we represent nodes etc...)
   - Is there anything on the section headers that would be annoying or make some people unhappy?

# During Reading:
 - Hassan:
    - Intro: was the motivation clear? Was previous work covered in the intro?
    - Graph overview: Is the overview enough? Do references about graph overview need to be added?
    - Are references consistent for all sections?
 - Amine:
    - Was the process of the simulation of selection on observables explained (including results)? Can the reader go and reproduce the simulation on their own afterwards? 
    -  Were the examples presented in the section good for the audience?
 - Tim:
    - Is there anything confusing in any of the sections? (For all as well)
    - Is there anything you find overly repetitive within a section? (For all as well)
- For all:
    - Is all content claimed to be covered actually covered?

Also anything from the previous comment in this issue.
# After Reading:
 - Hassan:
    - Latent confounding: Was the difficulty of dealing with latent confounding made clear?  Is what's provided as guidance on how to deal with confounding enough?
 - Amine:
    - Were we clear about the bias being about the causal effect as opposed to choice model parameter?
 - Tim:
    - Can the reader give 3 bullet points about the point of the sections?

**Comment by timothyb0912** [comment]
Hey all, I figured I'd leave this last set of review notes / requests here to finish us off.
cc @bouzaghrane and @hassan-obeid.

For Sunday December 6th, the following items are due:
- [x] Timothy
   - [x] Set up continuous integration for project.
   Just missing Hassan's public notebooks, and these should hopefully be merged this week.
   - [x] Review the compiled article as [present](https://github.com/hassan-obeid/tr_b_causal_2020/blob/90c5742cfe91f8e7821d38142b46fc1e31b2d10e/article/main.pdf) in #162.
- [ ] Hassan
   - [ ] Review (with special attention) Timothy's [abstract](https://github.com/hassan-obeid/tr_b_causal_2020/pull/157), experimentation for causal [discovery](https://github.com/hassan-obeid/tr_b_causal_2020/pull/156), and [discussion](https://github.com/hassan-obeid/tr_b_causal_2020/pull/154) sections.
   - [ ] Review the compiled article as [present](https://github.com/hassan-obeid/tr_b_causal_2020/blob/90c5742cfe91f8e7821d38142b46fc1e31b2d10e/article/main.pdf) in #162.
- [ ] Amine
   - [x] Respond to Hassan's [comments](https://github.com/hassan-obeid/tr_b_causal_2020/pull/150#pullrequestreview-540426104) on your sections.
   - [ ] Merge Hassan's public notebooks (along with updated requirements.(in|txt) file for tensorflow)
   - [ ] Review the compiled article as [present](https://github.com/hassan-obeid/tr_b_causal_2020/blob/90c5742cfe91f8e7821d38142b46fc1e31b2d10e/article/main.pdf) in #162.

Let me know if I'm missing anything (and feel free to edit this post).

When reviewing the article as a whole, please pay attention to:
   - errors that absolutely should not be in any publication
   - errors that we previously pointed out that were not addressed
   - unfulfilled promises
   - harsh disconnects between sentence, paragraphs, and sections.

**Comment by timothyb0912** [comment]
For pre-Dec-21st:
- [ ] Hassan
   - [ ] Finish addressing review of #124.
   - [ ] Respond to review comments on Section 3 [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/162#discussion_r536962725) by editing the branch and PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/176).
   - [ ] Respond to the unresolved review comments on Section 7 [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/162#pullrequestreview-545675160) by editing the branch and PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/177).
- [x] Timothy
   - [x] Respond to comments on section 4.
   - [x] (Check existence) Respond to comments on section 8.
   - [x] Finish reviewing sections 5, 6, and 8.
   - [x] ~Title.~
   See #164.
   - [x] ~Add Hassans public notebooks to CI.~
   Not going to do before the end of the year as actual edits need to be made to the notebook / code.

**Comment by timothyb0912** [comment]
Hey all, here is the plan going into the 8 days.
cc @bouzaghrane and @hassan-obeid.
Note the submission date change.
Let me know if any of you have questions / comments / suggestions / objections on below!

- [x] For today: Merge open and completed PRs with edits.

- [x] For Dec 19th:
   - [x] Timothy
      - [x] Make edits to Hassan's portions of Section 3.
      See #176.
      - [x] Place Amines edits for section 7 from #150 into new PR for section 7.
      See #177.
      - [x] Make edits to Section 7 in PR #177.
      - [x] [2]Add random seeds to Mo's and Hassan public notebooks.
   - [x] Amine
      - [x] Investigate making edits to Hassan's notebooks from the PR comments.
      Can it be made runnable on CI in public folder somewhat swiftly (a day or two's efforts?)
      - [x] Make edits to Section 9 about main comments in [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/162#pullrequestreview-545745082).
      - [x] Make minimal PR with edits to section 1 from #167.
      - [x] Read guide and familiarize self with getting a DOI for our repo.
      See comment [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/163#issuecomment-744049372).

- [x] For **PRE** Dec 21st:
   - [x] All
      - [x] [6]PR discussion / agreement on title.
      Please see and leave comments on #164.
      - [x] [4]Update font sizes in all graphs to 13 for legibility.
      - [x] [5]Ensure all graphs have consistent styling (white backgrounds etc.)
   - [x] Hassan
      - [x] Respond to review comments on Section 3 [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/162#discussion_r536962725) by editing the branch and PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/176).
      - [x] [1]Respond to the unresolved review comments on Section 7 [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/162#pullrequestreview-545675160) by editing the branch and PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/177).
      - [x] [3]~Finish addressing review comments on your public notebook PR #124.~
      ~Tag @timothyb0912 when you're finished with it for a final review before merging.~
      See completely separate PR in #183 that addresses the necessary comments to get plots with desired formatting for the paper.
      #124 left un-finished for now.
- [ ] On Dec 21st:
   - [x] Submit first complete chapter draft.
   - [ ] Have retrospective in evening.
   Perhaps 6pm - 8pm to accommodate Mo on the east coast?

**Comment by timothyb0912** [comment]
Closing due to inactivity in over a month.
(No moves have been made on rescheduling this retrospective, by any of us.)
